deploymentName: todo-server-gateway

replicaCount: 1

image:
  repository: mitsugu1128/todo-server-gateway
  pullPolicy: IfNotPresent
  tag: v0.0.13

service:
  # gatewayをNodePortにして外部に公開
  type: NodePort
  port: 8080
  targetPort: 8080