deploymentName: todo-server-api

replicaCount: 1

image:
  repository: mitsugu1128/todo-server-api
  pullPolicy: IfNotPresent
  tag: v0.0.13

service:
  # gatewayをNodePortにするので、ここはClusterIP
  type: ClusterIP
  port: 9090
  targetPort: 9090